### PR TITLE
Expansion Trader config for RaG_BaseItems

### PR DESCRIPTION
**Pull request by InnerSanctuary**
Expansion Trader .json file for RaG_BaseItems

https://steamcommunity.com/sharedfiles/filedetails/?id=2878980498

I found this in the RaG_BaseItems discord at discord.gg/MRfe4c9h3x

### CODE REVIEW

**Comment by LieutenantMaster** [comment]
Hello !

Could you fix the file as it doesnt end with a .json and put it inside a folder ?

**Comment by InnerSanctuary** [comment]
Im very sorry. This is the first time I've ever done a merge. I am not a programmer, im a network monkey. : P Honestly, I have no idea what im doing. I will try again.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by CommanderBeelo** [comment]
https://discord.com/channels/523890175563137034/874389707763634246/1183468658194911372

@InnerSanctuary  check this quick how-to in the expansion discord.

**Comment by InnerSanctuary** [comment]
Hey CommanderBeelo, 

thanks for the info but... that channel (-ht-community-sharing) is hidden to me.  I also cannot view it or see it anywhere in your discord server.  I have re-summitted this change request and think I got it right this time.  My discord is GM$oneyYo if you wanna allow me to see it.

I'll be submitting more changes for other mods soon.

**Comment by CommanderBeelo** [comment]
@InnerSanctuary stop in the meta-role channel in the discord and click the server owner role, it will open a whole new section or two up for you. I also took the time to add the same how-to to this repo. 

Basically, go to your repo, delete the file your trying to add from your repo. doing stuff from the browser is a pain in the ass sometimes. 

Github Desktop https://desktop.github.com/ is a little easier to use once you get used to it, it lets you have a local copy of your repository on your local machine, you make all your edits to those files, and then use the same app to push it back to your repo and open a pull request.


PS sorry for the slow reply, I didnt see the email for it

**Comment by InnerSanctuary** [comment]
YOU GAVE ME MY FIRST STAR ON GITHUB!!!! IM SO PROUD!  THANK YOU!  I'm like a Jr. Programmer now! : )

OMG your instructions are awesome!!!!! Should i delete the one i did and resubmit?

**Comment by InnerSanctuary** [comment]
OMG your instructions are awesome!!!!! Should i delete the one i did and resubmit?

**Comment by CommanderBeelo** [comment]
I am fairly certain once you fixed your repo it'll update the pull request
automatically.

**Comment by CommanderBeelo** [comment]
I fixed this for you @InnerSanctuary - https://github.com/ExpansionModTeam/DayZ-Expansion-Unofficial-Market-Settings/pull/39

**Comment by LieutenantMaster** [comment]
Merged from https://github.com/ExpansionModTeam/DayZ-Expansion-Unofficial-Market-Settings/pull/39

**Pull request closed without merging**
